# Bison handling

MACRO(FIND_BISON)
	IF(NOT BISON_EXECUTABLE)
		MESSAGE("-- Looking for bison executable")
		FIND_PROGRAM(BISON_EXECUTABLE bison)
		IF(NOT BISON_EXECUTABLE)
			MESSAGE(FATAL_ERROR "bison not found - aborting")
		ENDIF(NOT BISON_EXECUTABLE)
	ENDIF(NOT BISON_EXECUTABLE)
ENDMACRO(FIND_BISON)

MACRO(ADD_BISON_SOURCE f_src f_dest)
	ADD_CUSTOM_COMMAND(SOURCE ${f_src}
		COMMAND ${BISON_EXECUTABLE}
		ARGS ${f_src} -o ${f_dest}
		OUTPUT ${f_dest})
	SET_SOURCE_FILES_PROPERTIES(${f_dest} GENERATED)
ENDMACRO(ADD_BISON_SOURCE f_src f_dest)
