MACRO(LEMON_PARSER SRCFILE)
    GET_FILENAME_COMPONENT(SRCBASE ${SRCFILE} NAME_WE)
    ADD_CUSTOM_COMMAND(OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${SRCBASE}.c ${CMAKE_CURRENT_BINARY_DIR}/${SRCBASE}.h
        COMMAND ${CMAKE_BINARY_DIR}/lemon
        ARGS -q ${CMAKE_CURRENT_SOURCE_DIR}/${SRCFILE} ${CMAKE_SOURCE_DIR}/lemon/lempar.c
        DEPENDS ${CMAKE_BINARY_DIR}/lemon ${CMAKE_CURRENT_SOURCE_DIR}/${SRCFILE} ${CMAKE_SOURCE_DIR}/lemon/lempar.c
        COMMENT "Generating ${SRCBASE}.c from ${SRCFILE}"
    )
ENDMACRO(LEMON_PARSER)
